GLOBAL:
  type: client # Client / Server or both
  db_path: /etc/ansible-lite/db.sqlite3
  log_path: /etc/ansible-lite/log.log
  log_level: info
  repos_config: repos.yaml
  port: 8080 # Used only for server
  credentials:
  # ssl: false 
  # cert: data/cert.pem
  # key: data/key.pem